/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;


public class asociacion extends javax.swing.JFrame {

    /**
     * Creates new form procesodeAsociacion
     */
    public asociacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCatalogo = new javax.swing.JComboBox<>();
        cbProducto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txValorProd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txPuntosGa = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txPuntosRe = new javax.swing.JTextField();
        btConsultaAso = new javax.swing.JButton();
        btAsociar = new javax.swing.JButton();
        btEliminarA = new javax.swing.JButton();
        btAtrasA = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel1.setText("Asociación del producto al catálogo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel2.setText("Nombre del catálogo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel3.setText("Nombre del producto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        cbCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCatalogoActionPerformed(evt);
            }
        });
        getContentPane().add(cbCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 82, -1));

        getContentPane().add(cbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 82, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel4.setText("Valor del producto:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(txValorProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 132, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel5.setText("Puntos ganados:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        getContentPane().add(txPuntosGa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 132, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        jLabel6.setText("Puntos para redimirlo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));
        getContentPane().add(txPuntosRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 119, -1));

        btConsultaAso.setBackground(new java.awt.Color(51, 51, 51));
        btConsultaAso.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        btConsultaAso.setForeground(new java.awt.Color(255, 255, 255));
        btConsultaAso.setText("CONSULTA");
        getContentPane().add(btConsultaAso, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 97, -1));

        btAsociar.setBackground(new java.awt.Color(51, 51, 51));
        btAsociar.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        btAsociar.setForeground(new java.awt.Color(255, 255, 255));
        btAsociar.setText("ASOCIAR");
        getContentPane().add(btAsociar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 97, -1));

        btEliminarA.setBackground(new java.awt.Color(51, 51, 51));
        btEliminarA.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        btEliminarA.setForeground(new java.awt.Color(255, 255, 255));
        btEliminarA.setText("ELIMINAR");
        btEliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarAActionPerformed(evt);
            }
        });
        getContentPane().add(btEliminarA, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        btAtrasA.setBackground(new java.awt.Color(51, 51, 51));
        btAtrasA.setFont(new java.awt.Font("Courier New", 1, 11)); // NOI18N
        btAtrasA.setForeground(new java.awt.Color(255, 255, 255));
        btAtrasA.setText("ATRAS");
        btAtrasA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtrasAActionPerformed(evt);
            }
        });
        getContentPane().add(btAtrasA, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 12, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre catálogo", "Nombre producto", "Valor Producto", "Puntos Ganados", "Puntos Redimir"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 507, 95));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAtrasAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtrasAActionPerformed
        
    }//GEN-LAST:event_btAtrasAActionPerformed

    private void cbCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCatalogoActionPerformed

    private void btEliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEliminarAActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAsociar;
    public javax.swing.JButton btAtrasA;
    public javax.swing.JButton btConsultaAso;
    public javax.swing.JButton btEliminarA;
    public javax.swing.JComboBox<String> cbCatalogo;
    public javax.swing.JComboBox<String> cbProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField txPuntosGa;
    public javax.swing.JTextField txPuntosRe;
    public javax.swing.JTextField txValorProd;
    // End of variables declaration//GEN-END:variables
}
