package Vistas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author WIN-10 GENERATION
 */
public class Catalogo extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GEstado = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btActivo = new javax.swing.JRadioButton();
        btNoActivo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreDelCatalogo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTlistaCatalogo = new javax.swing.JTable();
        btConsultar = new javax.swing.JButton();
        btEliminar = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        txConsulta = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btCrearCatalogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Catalogo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 12, -1, -1));

        GEstado.add(btActivo);
        btActivo.setText("Activo");
        btActivo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                btActivoComponentMoved(evt);
            }
        });
        getContentPane().add(btActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 147, -1, -1));

        GEstado.add(btNoActivo);
        btNoActivo.setText("No Activo");
        getContentPane().add(btNoActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel2.setText("Nombre del Catalogo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 120, -1));

        jLabel3.setText("Fecha");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, -1));

        jLabel4.setText("Estado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 99, -1));
        getContentPane().add(txtNombreDelCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, -1));
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, -1));

        JTlistaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Del Catalogo", "Fecha", "Estado"
            }
        ));
        jScrollPane1.setViewportView(JTlistaCatalogo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 90));

        btConsultar.setText("Consulta");
        getContentPane().add(btConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btEliminar.setText("Eliminar");
        getContentPane().add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, -1));

        btModificar.setText("Modificar");
        getContentPane().add(btModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, -1));

        txConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(txConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 150, 20));

        jButton4.setText("Atras");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, -1, -1));

        btCrearCatalogo.setText("Crear");
        getContentPane().add(btCrearCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActivoComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btActivoComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btActivoComponentMoved

    private void txConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GEstado;
    public javax.swing.JTable JTlistaCatalogo;
    public javax.swing.JRadioButton btActivo;
    public javax.swing.JButton btConsultar;
    public javax.swing.JButton btCrearCatalogo;
    public javax.swing.JButton btEliminar;
    public javax.swing.JButton btModificar;
    public javax.swing.JRadioButton btNoActivo;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField txConsulta;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtNombreDelCatalogo;
    // End of variables declaration//GEN-END:variables
}
